-- 0. Desactivar temporalmente la regla de Primary Key y verificaciones de llaves foráneas para Aiven
SET SESSION sql_require_primary_key = OFF;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. TABLA REGISTRO_USUARIO
CREATE TABLE IF NOT EXISTS REGISTRO_USUARIO (
    ID_USUARIO INT PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    EDAD INT,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    TELEFONO VARCHAR(15),
    PASSWORD VARCHAR(255) NOT NULL,
    ROL VARCHAR(20) DEFAULT 'cliente'
);

-- 2. TABLA ANALISTA
CREATE TABLE IF NOT EXISTS ANALISTA (
    ID_ANALISTA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    DEPARTAMENTO VARCHAR(50) DEFAULT 'Riesgo y Crédito',
    FOREIGN KEY (ID_USUARIO) REFERENCES REGISTRO_USUARIO(ID_USUARIO)
);

-- 3. TABLA CUENTA
CREATE TABLE IF NOT EXISTS CUENTA (
    ID_CUENTA VARCHAR(40) PRIMARY KEY,
    ID_USUARIO INT,
    TIPO_CUENTA VARCHAR(80),
    SALDO DECIMAL(12,2) DEFAULT 0.00,
    FOREIGN KEY (ID_USUARIO) REFERENCES REGISTRO_USUARIO(ID_USUARIO)
);

-- 4. TABLA CREDITO
CREATE TABLE IF NOT EXISTS CREDITO (
    ID_CREDITO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT,
    NOMBRE_COMPLETO VARCHAR(150),
    ID_ANALISTA INT NULL,
    INGRESOS DECIMAL(12,2),
    MONTO_SOLICITADO DECIMAL(12,2),
    ESTADO VARCHAR(40) DEFAULT 'Pendiente',
    OCUPACION VARCHAR(100),
    TELEFONO VARCHAR(20),
    FECHA_SOLICITUD DATE,
    FOREIGN KEY (ID_USUARIO) REFERENCES REGISTRO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA(ID_ANALISTA)
);

-- 5. TABLA CUOTAS
CREATE TABLE IF NOT EXISTS CUOTAS (
  ID_CUOTA INT AUTO_INCREMENT PRIMARY KEY,
  ID_CREDITO INT NOT NULL,
  NUMERO_CUOTA INT NOT NULL,
  MONTO_CUOTA DECIMAL(12, 2) NOT NULL,
  FECHA_VENCIMIENTO DATE NOT NULL,
  ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
  FECHA_PAGO DATETIME NULL,
  FOREIGN KEY (ID_CREDITO) REFERENCES CREDITO(ID_CREDITO) ON DELETE CASCADE
);

-- 6. TABLA PAGO
CREATE TABLE IF NOT EXISTS PAGO (
    ID_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CREDITO INT,
    FECHA DATE,
    MONTO DECIMAL(15,2),
    METODO VARCHAR(40),
    FOREIGN KEY (ID_CREDITO) REFERENCES CREDITO(ID_CREDITO)
);

-- 7. TABLA TRANSACCION
CREATE TABLE IF NOT EXISTS TRANSACCION (
    ID_TRANSACCION INT PRIMARY KEY AUTO_INCREMENT,
    ID_CUENTA VARCHAR(40),
    FECHA DATE,
    MONTO DECIMAL(15,2),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID_CUENTA)
);

-- Volver a activar las verificaciones de llaves foráneas
SET FOREIGN_KEY_CHECKS = 1;

-- ========================================================
-- INSERCIÓN DE DATOS DE PRUEBA 
-- ========================================================

-- Insertar Usuarios (Clientes y 1 Analista)
INSERT INTO REGISTRO_USUARIO 
(ID_USUARIO, NOMBRE, APELLIDO, EDAD, EMAIL, TELEFONO, PASSWORD, ROL)
VALUES
(1014298336, 'Juan', 'Leon', 27, 'juanpablo30_10@hotmail.com', '3001234567', '123456', 'cliente'),
(39548678, 'Maria', 'Gomez', 32, 'maria@gmail.com', '3109876543', '123456', 'cliente'),
(1000394226, 'Carlos', 'Ramirez', 19, 'carlos@outlook.com', '3114567890', '123456', 'cliente'),
(999999999, 'Analista', 'Brocash', 35, 'analista@brocash.com', '3000000000', 'admin123', 'analista');

SET FOREIGN_KEY_CHECKS = 1;
